config/routes.rb
KardexIII::Application.routes.draw do
  resources :equipement_vaut_pours

  resources :vaut_pours

  resources :est_monte_surs do 
	  collection do
		  get 'val_pot'
	  end
  end
  

  resources :equipements

  resources :visite_equipements do 
	  collection do
		get  'get_visite_equ'
		get 'get_type_visite'
	end
end

  resources :exec_cn_equipements do 
	  collection do
		get  'cn_type_equipement'
	end
end
  
  

  resources :cn_equipements

  resources :potentiel_equipements

  resources :visite_protocolaire_equipements

  resources :type_equipements

  resources :modif_repars

  resources :visite_machines do
	  collection do
		  get 'get_type_visite'
		  get 'get_type_machine'
	  end
  end
  

  resources :exec_cn_machines do
	collection do
		get 'cn_typemachine'
	end
end

  resources :doc_divers do
	  collection do
		  get 'envoi_doc'
		  post 'save_doc'
		  post 'suppr_doc'
	  end
  end
  
  resources :potentiel_machines 
  
  resources :type_potentiels  do
	  collection do
		  get 'get_unitee'
	  end
  end

  resources :cn_machines

  resources :visite_protocolaires

  resources :type_machines

  resources :machines

  resources :carnets

  resources :page_acces

  resources :personnes

resources :personnes do
end

resources :appli do
  collection do
    get 'login'
    post 'login'
    post 'create_new'
    get 'logout'
    get 'welcome'
    get 'bandeau_gauche'
  end
end
resources :machines do
end

  root :to => 'appli#welcome'
end

app/models/est_monte_sur.rb
class EstMonteSur < ActiveRecord::Base
	belongs_to:machine, :foreign_key =>:idmachine
	belongs_to:equipement, :foreign_key =>:idequipement
	has_many :potentiel_montage, :foreign_key=>:idest_monte_sur
	validates_presence_of :idmachine ,:message => "la machine doit être définie"
	validates_presence_of :idequipement ,:message => "l'équipement doit être défini"
end

app/controllers/est_monte_surs_controller.rb
class EstMonteSursController < ApplicationController
  before_action :set_est_monte_sur, only: [:show, :edit, :update, :destroy]
  before_filter :page_acc
  # GET /est_monte_surs
  # GET /est_monte_surs.json
  def index
    @montage_equipements =  EstMonteSur.all
    @montage_equipements=@montage_equipements.sort_by{|montage|  [montage.machine.type_machine.type_machine,montage.machine.Immatriculation]}
  end

  # GET /est_monte_surs/1
  # GET /est_monte_surs/1.json
  def show
	@vis_equip= VisiteEquipement.find(:all,:conditions=>["idequipement=? and nom=?",@montage_equipement.idequipement,"visite montage"])
  end

  # GET /est_monte_surs/new
  def new
   @est_monte_sur = EstMonteSur.new
  @tableau_mois=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Aout","Septembre","Octobre","Novembre","Décembre"]

  end

  # GET /est_monte_surs/1/edit
  def edit
	#on initialise
	@couple=Hash.new()
	@tableau_mois=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Aout","Septembre","Octobre","Novembre","Décembre"]
	#on récupère le montage en cause 
	@est_monte_sur  = EstMonteSur.find(params[:id])
	#on récupère les éléments de potentiels 
	@elt_pot=@est_monte_sur.potentiel_montage
	#on récupère les éléments liée aux visites protocolaires
	@couple[:idmachine]=@est_monte_sur.idmachine
	@couple[:idequipement]=@est_monte_sur.idequipement
	set_pot(@couple)
	 
  end

  # POST /est_monte_surs
  # POST /est_monte_surs.json
  def create
    @est_monte_sur = EstMonteSur.new(est_monte_sur_params)
    @pots=params[:pot]
    #raise @pots.inspect
    @prot=params[:potentiel_montage_vis]
    respond_to do |format|
      if @est_monte_sur.save
	       j=0
		if !@pots.nil? then
			@pots.each do |pot|
				#raise pot[1].inspect
				@res=PotentielMontage.new()
				@res.idest_monte_sur = @est_monte_sur[:id]
				@res.idpotentiel_equipement = pot[1][:idpotentiel_equipement]
				#présent 
				@res.valeur_potentiel_montage=pot[1][:valeur_potentiel_montage]
				@res.valeur_machine_jour_montage= pot[1][:valeur_machine_jour_montage]
				#pas dispo 
				@res.idtype_potentiel=pot[1][:idtype_potentiel]
				
				@res.save
				j=j+1
			end
		end
		#on crée des visites protocolaires bidon pour démarrer les potentiels
		if !@prot.nil?
			#on récupère toutes visites protocolaires
			@equipement=Equipement.find(@est_monte_sur[:idequipement])
			#on crée une visite bidon par visites protocolaires
			@vis_pro=@equipement.type_equipement.visite_protocolaire_equipement
			@vis_pro.each do |vi_pro|
				#on cree une visite
				@vis_equip=VisiteEquipement.new
				@vis_equip.idequipement=@est_monte_sur[:idequipement]
				@vis_equip.date_visite=@est_monte_sur.date_montage
				@vis_equip.idtype_potentiel=vi_pro.idtype_potentiel
				#valeur de réalisation
				@val=@prot[vi_pro.idtype_potentiel.to_s]
				@vis_equip.val_potentiel=@val[:valeur_machine_jour_montage]
				@vis_equip.id_visite_protocolaire_equipement=vi_pro.id
				@vis_equip.nom="visite montage"
				@vis_equip.save
			end
			
		end
        format.html { redirect_to @est_monte_sur, notice: 'Est monte sur was successfully created.' }
        format.json { render action: 'show', status: :created, location: @est_monte_sur }
      else
        format.html { render action: 'new' }
        format.json { render json: @est_monte_sur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /est_monte_surs/1
  # PATCH/PUT /est_monte_surs/1.json
  def update
    respond_to do |format|
      if  @montage_equipement.update(est_monte_sur_params)
        format.html { redirect_to  @montage_equipement, notice: 'Montage correctement mis à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @est_monte_sur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /est_monte_surs/1
  # DELETE /est_monte_surs/1.json
  def destroy
     @montage_equipement.destroy
    respond_to do |format|
      format.html { redirect_to est_monte_surs_url }
      format.json { head :no_content }
    end
  end
  def val_pot
	@couple=Hash.new()
	@elt_pot=Array.new()
	#on récupère entrée l'id machine et l'id équipement 
	  #on regarde s'il existe un montage correspondant 
	@est_monte_sur = EstMonteSur.find(:first,:conditions=>["date_retrait is null and idequipement = ? and idmachine = ? " ,  params[:equip_id] , params[:mach_id]] )
	if (@est_monte_sur.nil?) then 
		releve=Carnet.liste_machine_carnet(params[:mach_id])
		#si non on récupére  pour l'équipement les potentiels
		equipement=Equipement.find( params[:equip_id])
		potentiel_equi=equipement.type_equipement.potentiel_equipement
		i=0
		potentiel_equi.each do |po_equi|
			potentiel=PotentielMontage.new()
			potentiel.potentiel_equipement=PotentielEquipement.new()
			potentiel.idpotentiel_equipement=po_equi.id
			potentiel.potentiel_equipement.type_potentiel=po_equi.type_potentiel
			potentiel.valeur_potentiel_montage=po_equi.valeur_potentiel
			if po_equi.type_potentiel.type_potentiel=="Calendaire" then 
				potentiel.valeur_machine_jour_montage=0
			elsif po_equi.type_potentiel.type_potentiel=="utilisation moteur" then
				potentiel.valeur_machine_jour_montage=releve["heure_moteur"]
			elsif po_equi.type_potentiel.type_potentiel=="Heure de vol" then 
				potentiel.valeur_machine_jour_montage=releve["heure_de_vol"]
			elsif po_equi.type_potentiel.type_potentiel=="Nb cycles" then
				potentiel.valeur_machine_jour_montage=releve["nombre_cycle"]
			else
				potentiel.valeur_machine_jour_montage=0
			end
			
			potentiel.id=i
			i=i+1
			@elt_pot.push(potentiel)
		end
		#2) les potentiels du type d'équipement
		@couple[:idmachine]= params[:mach_id]
		@couple[:idequipement]= params[:equip_id]
		set_pot(@couple)
	 else
		@elt_pot=@est_monte_sur.potentiel_montage
		#on récupère les éléments liée aux visites protocolaires
		@couple[:idmachine]=@est_monte_sur.idmachine
		@couple[:idequipement]=@est_monte_sur.idequipement
		set_pot(@couple)
	end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_est_monte_sur
      @montage_equipement = EstMonteSur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def est_monte_sur_params
      params[:est_monte_sur].permit(:idequipement,:idmachine,:date_montage,:date_retrait)
    end
    def set_pot(id_montage_equi)
     @param=id_montage_equi
	 if (@param[:idmachine]!="" and @param[:idequipement]!="" and @param[:idmachine]!="0" and @param[:idequipement]!="0" ) then 
		 @ok=true
		 @releve=Carnet.liste_machine_carnet(@param[:idmachine])
		 #initialisation
		 @tot=Hash.new
		 j=0
		 #on identifie les potentiels à récup
		 @equipement=Equipement.find(@param[:idequipement])
		 #on récupère les types de potentiels equipement
		 @pots=@equipement.type_equipement.potentiel_equipement
		 #il faut aussi récupérer les types de potentiels des visites protocoliare de cetype d'équipement
		@vis_prot=@equipement.type_equipement.visite_protocolaire_equipement
		@vis_prot.each do |pot|
			@A_faire=Hash.new
			 @A_faire["typ_pot"]=pot.type_potentiel.type_potentiel
			 if (pot.type_potentiel.type_potentiel=="Calendaire") then @val=0
			elsif (pot.type_potentiel.type_potentiel=="Nb cycles") then @val=@releve["nombre_cycle"].to_s
			elsif (pot.type_potentiel.type_potentiel=="Heure de vol") then @val=@releve["heure_de_vol"].to_s
			else @val= @releve["heure_moteur"].to_s
			end
			@A_faire["valeur_carnet_montage"]= @val
			@A_faire["id_pot"]=pot.type_potentiel.id
			 @tot[pot.type_potentiel.id]=@A_faire
			 j=j+1
		  end
		 #on récupère les valeurs du dernier relevé
		 @releve=Carnet.liste_machine_carnet(@param[:idmachine])
		 @potos=params[:potentiel_montage]
	else
		@ok=false
	end
end
end

app/helpers/est_monte_surs_helper.rb
module EstMonteSursHelper
end

app/views/est_monte_surs/_form.html.erb
<%= form_for(@est_monte_sur) do |f| %>
  <% if @est_monte_sur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@est_monte_sur.errors.count, "error") %> prohibited this est_monte_sur from being saved:</h2>

      <ul>
      <% @est_monte_sur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border=1>
<tr><td>
<label for="idequipement">Equipement:</label></td>
<td>
<%=  f.select "idequipement", Equipement.includes(:type_equipement).all(:order =>"type_equipements.nom_constructeur,type_equipements.type_equipement,num_serie DESC").collect {|p| [p.type_equipement.nom_constructeur+" "+p.type_equipement.type_equipement+" " + p.num_serie, p.id ] },{:include_blank=> 'None'}%><br/>
</td></tr>
<tr><td>
<label for="idmachine">Machine :</label></td>
<td>
<%=  f.select( "idmachine", Machine.includes(:type_machine).all(:order => "type_machines.type_machine,Immatriculation DESC").collect {|p| [ p.type_machine.type_machine+" "+p.Immatriculation,p.id ] },{:include_blank=> 'None'})%><br/>
</td></tr>
<tr><td>
<label for="date_montage">Mont&eacute le  :</label></td>
<td><%= f.date_select  "date_montage", :order => [:day,:month,:year],:start_year => 1950, :use_month_names=>@tableau_mois %>
</td></tr>
<tr><td>
<label for="date_retrait">retrait le  :</label></td>
<td><%= f.date_select "date_retrait", :order => [:day,:month,:year],:start_year => 1950, :use_month_names=>@tableau_mois,:include_blank=>' ' %>
</td></tr>
</table>
<h2> Mise &agrave; jour des potentiels</h2>
<div id="val_pot">
 <%= render "form_pot" %>
</div>
  <div class="actions">
    <%= f.submit("Enregistrer") %>
  </div>
<% end %>

app/views/est_monte_surs/_form_pot.html.erb
<h3>Potentiel<h3>
<% if !@elt_pot.nil? and  !@elt_pot.empty?  then %>
<table border=1>
<td>type de potentiel</td>
<td>Valeur du potentiel machine au jour de montage</td>
<td>Potentiel restant au montage</td>
<% @elt_pot.each do |pot| %>
<tr>
		<td><%= pot.potentiel_equipement.type_potentiel.type_potentiel%></td>
		<td><%= text_field "pot["+pot.id.to_s+"]", :valeur_machine_jour_montage , :value=>pot.valeur_machine_jour_montage.to_s, :size => 20 %>
		<td><%= text_field "pot["+pot.id.to_s+"]", :valeur_potentiel_montage , :value=>pot.valeur_potentiel_montage.to_s, :size => 20 %></td>
		<%= hidden_field_tag("pot["+pot.id.to_s+"][idpotentiel_equipement]",pot.idpotentiel_equipement) %>
	</tr>

<%end%>
</table>
<%end%>
<h3> valeur carnet pour visites protocolaires </h3><% if !@tot.nil? then %>
<table border=1>
<tr>
	<td>Type potentiel</td>
	<td>Valeur carnet au montage</td>
</tr>	
<% @tot.each do |recup_pot_visite| %>
<tr>
	<td><%= recup_pot_visite[1]["typ_pot"] %></td>
	<td><%= text_field_tag("[potentiel_montage_vis]["+recup_pot_visite[1]["id_pot"].to_s+"[valeur_machine_jour_montage]",recup_pot_visite[1]["valeur_carnet_montage"] ) %></td>
	<%= hidden_field_tag("[potentiel_montage_vis]["+recup_pot_visite[1]["id_pot"].to_s+"][idtype_potentiel]", recup_pot_visite[1]["typ_pot"]) %>
	
</tr>
<% end %>
</table>
<%end%>

app/views/est_monte_surs/edit.html.erb
<h1>modifier un montage</h1>


<%= render 'form' %>

<%= link_to 'détails', @est_monte_sur %> |
<%= link_to 'retour à liste', est_monte_surs_path %>

app/views/est_monte_surs/index.html.erb
<h1>liste des &eacute;quipements mont&eacute;s</h1>
<%= link_to 'nouveau montage', new_est_monte_sur_path %>
<% immat="" %>

<% @montage_equipements.each do |montage_equipement| %>
	
	<% if (immat!= montage_equipement.machine.Immatriculation) then %>
		<% if ( immat!="") then %>
			</table>
		<%end %>
		<% immat=montage_equipement.machine.Immatriculation %>
		<h3> Equipements mont&eacute;s sur <%= montage_equipement.machine.type_machine.type_machine %> <%= montage_equipement.machine.Immatriculation%> </h3>
		<table border=1 width=80%>
		 <tr>
			<td width=15%>Constructeur</td>
			<td width=17%>type &eacute;quipement</td>
			<td width=23%>num s&eacute;rie</td>
			<td width=12%>date montage</td>
			<td width=12%>date retrait</td>
			<td width=6%>&nbsp;</td>
			<td width=6%>&nbsp;</td>
			<td width=6%>&nbsp;</td>
		  </tr>
<% end %>
  <tr>
    <td><%= montage_equipement.equipement.type_equipement.nom_constructeur    %></td>
    <td><%= montage_equipement.equipement.type_equipement.type_equipement    %></td>
    <td><%= montage_equipement.equipement.num_serie    %></td>
    <td><%= if (montage_equipement.date_montage.nil?) then " " else  montage_equipement.date_montage.strftime('%d/%m/%Y')  end   %></td>
    <td><%= if (montage_equipement.date_retrait.nil?) then " " else montage_equipement.date_retrait.strftime('%d/%m/%Y') end   %></td>
    <td><%= link_to 'détail', montage_equipement %></td>
    <td><%= link_to 'Modifier', edit_est_monte_sur_path(montage_equipement) %></td>
    <td><%= link_to 'suppr', montage_equipement, :confirm => 'etes vous sur ?', :method => :delete %></td>
  </tr>


<% end %>
</table>
<br />

app/views/est_monte_surs/new.html.erb
<h1>Nouveau montage d'équipement</h1>

<%= render 'form' %>

<%= link_to 'retour à liste', est_monte_surs_path %>

app/views/est_monte_surs/show.html.erb
<H1> Détail montage équipement <%=@montage_equipement.equipement.type_equipement.nom_constructeur%>  <%=@montage_equipement.equipement.type_equipement.type_equipement%></h1>
<table border=1>
	 <tr>
		<td width=15%>Type</td>
		<td width=15%>Immat</td>
		<td> Constructeur</td>
		<td width=17%>type &eacute;quipement</td>
		<td width=23%>num s&eacute;rie</td>
		<td width=12%>date montage</td>
		<td width=12%>date retrait</td>
	  </tr>
<tr>
	 <td><%= @montage_equipement.machine.type_machine.type_machine %></td>
	 <td><%= @montage_equipement.machine.Immatriculation%> </td>
	 <td><%= @montage_equipement.equipement.type_equipement.nom_constructeur    %></td>
	 <td><%= @montage_equipement.equipement.type_equipement.type_equipement    %></td>
	 <td><%= @montage_equipement.equipement.num_serie    %></td>
	 <td><%= if (@montage_equipement.date_montage.nil?) then "&nbsp;" else  @montage_equipement.date_montage.strftime('%d/%m/%Y')  end   %></td>
	<td><%= if (@montage_equipement.date_retrait.nil?) then " " else @montage_equipement.date_retrait.strftime('%d/%m/%Y') end   %></td>
</tr>
</table>
<h3> potentiel au montage </h3>
<table border=1>
<tr>
	<td>Type potentiel</td>
	<td>potentiel restant au montage</td>
	<td>Valeur carnet au montage</td>
</tr>	

<% @montage_equipement.potentiel_montage.each do |pot| %>
	<tr>
		<td><%= pot.potentiel_equipement.type_potentiel.type_potentiel %></td>
		<td><%=pot.valeur_potentiel_montage%></td>
		<td><%= if (pot.potentiel_equipement.type_potentiel.type_potentiel=="Calendaire") then @montage_equipement.date_montage.strftime('%d/%m/%Y') else pot.valeur_machine_jour_montage end%></td>
	</tr>
<% end %>
</table>
<h3> visite entretien réalisé au montage </h3>
<table border=1>
<tr>
	<td>Type de visites</td>
	<td>type de potentiel</td>
	<td>Périodicité visite</td>
	<td>Valeur carnet au montage</td>
	<td>&nbsp;</td>
</tr>	
<% @vis_equip.each do |vis| %>
	<tr>
	<td><%= vis.visite_protocolaire_equipement.Nom%></td>
	<td><%= vis.visite_protocolaire_equipement.type_potentiel.type_potentiel%></td>
	<td><%= vis.visite_protocolaire_equipement.valeur_potentiel%></td>
	<td><%= vis.val_potentiel %></td>
	<td><%= link_to 'modifier', edit_visite_equipement_path(vis) %></td>
</tr>	
<%end%>
</table>
<%= link_to 'Modifier', edit_est_monte_sur_path(@montage_equipement) %> |
<%= link_to 'retour à la liste', est_monte_surs_path %>

app/views/est_monte_surs/val_pot.js.erb
$( '#val_pot' ).html(" <%= escape_javascript(render "form_pot") %>");