config/routes.rb
KardexIII::Application.routes.draw do
  resources :equipement_vaut_pours

  resources :vaut_pours

  resources :est_monte_surs do 
	  collection do
		  get 'val_pot'
	  end
  end
  

  resources :equipements

  resources :visite_equipements do 
	  collection do
		get  'get_visite_equ'
		get 'get_type_visite'
	end
end

  resources :exec_cn_equipements do 
	  collection do
		get  'cn_type_equipement'
	end
end
  
  

  resources :cn_equipements

  resources :potentiel_equipements

  resources :visite_protocolaire_equipements

  resources :type_equipements

  resources :modif_repars

  resources :visite_machines do
	  collection do
		  get 'get_type_visite'
		  get 'get_type_machine'
	  end
  end
  

  resources :exec_cn_machines do
	collection do
		get 'cn_typemachine'
	end
end

  resources :doc_divers do
	  collection do
		  get 'envoi_doc'
		  post 'save_doc'
		  post 'suppr_doc'
	  end
  end
  
  resources :potentiel_machines 
  
  resources :type_potentiels  do
	  collection do
		  get 'get_unitee'
	  end
  end

  resources :cn_machines

  resources :visite_protocolaires

  resources :type_machines

  resources :machines

  resources :carnets

  resources :page_acces

  resources :personnes

resources :personnes do
end

resources :appli do
  collection do
    get 'login'
    post 'login'
    post 'create_new'
    get 'logout'
    get 'welcome'
    get 'bandeau_gauche'
  end
end
resources :machines do
end

  root :to => 'appli#welcome'
end

app/controllers/exec_cn_machines_controller.rb
class ExecCnMachinesController < ApplicationController
  before_action :set_exec_cn_machine, only: [:show, :edit, :update, :destroy]
  before_filter :page_acc

  # GET /exec_cn_machines
  # GET /exec_cn_machines.json
  def index
    @exec_cn_machines = ExecCnMachine.all.includes({cn_machine:  [:type_machine,:type_potentiel]},:machine )
    @exec_cn_machines=@exec_cn_machines.sort_by{|exec_cn_machine| [exec_cn_machine.machine.type_machine.type_machine,exec_cn_machine.machine.Immatriculation,exec_cn_machine.cn_machine.nom]}
  end

  # GET /exec_cn_machines/1
  # GET /exec_cn_machines/1.json
  def show
	  
  end

  # GET /exec_cn_machines/new
  def new
	@tableau_mois=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Aout","Septembre","Octobre","Novembre","Décembre"]
	@exec_cn_machine = ExecCnMachine.new
	 if !(params[:id_machine].nil?) then 
		@exec_cn_machine.id_machine=params[:id_machine]
	end
	@exec_cn_machine.val_potentiel_exec=0
	@unite="&nbsp;"
	if !(params[:idcn_machine].nil?) then 
		@exec_cn_machine.idcn_machine=params[:idcn_machine]
		#recup type de protentiel lié à la visite 
		@visite_prot=CnMachine.find(params[:idcn_machine])
		@unite=@visite_prot.type_potentiel.unitee_saisie
	end
  end

  # GET /exec_cn_machines/1/edit
  def edit
	   @tableau_mois=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Aout","Septembre","Octobre","Novembre","Décembre"]
  end

  # POST /exec_cn_machines
  # POST /exec_cn_machines.json
  def create
    @exec_cn_machine = ExecCnMachine.new(exec_cn_machine_params.permit(:id_machine,:idcn_machine,:idtype_potentiel,:val_potentiel_exec,:date_exec,:non_applicable,:commentaire))

    respond_to do |format|
      if @exec_cn_machine.save
        format.html {
		if (params[:retour].nil?) then 
			redirect_to @exec_cn_machine, notice: 'Exécution de CN correctement enregistrée' 
		else
			#renvoi vers la page détails machine
			redirect_to url_for(:controller => 'machines',:action=>"show", :id => params[:retour],:onglet =>2), :notice => 'Execution CN machine pris en compte.'
		end
	}
        format.json { render action: 'show', status: :created, location: @exec_cn_machine }
      else
        format.html { render action: 'new' }
        format.json { render json: @exec_cn_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exec_cn_machines/1
  # PATCH/PUT /exec_cn_machines/1.json
  def update
    respond_to do |format|
      if @exec_cn_machine.update(exec_cn_machine_params.permit(:id_machine,:idcn_machine,:idtype_potentiel,:val_potentiel_exec,:date_exec,:non_applicable,:commentaire))
        format.html { redirect_to @exec_cn_machine, notice: 'Exécution de CN mis à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exec_cn_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exec_cn_machines/1
  # DELETE /exec_cn_machines/1.json
  def destroy
    @exec_cn_machine.destroy
    respond_to do |format|
      format.html { redirect_to exec_cn_machines_url }
      format.json { head :no_content }
    end
  end
  def cn_typemachine
	@machine=Machine.find(params[:machine_id])
	@cn_machines=CnMachine.find(:all, :conditions => ['idtype_machine = ? ',@machine.type_machine.id])
	  respond_to do |format|
		format.js 
	end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exec_cn_machine
      @exec_cn_machine = ExecCnMachine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exec_cn_machine_params
      params[:exec_cn_machine]
    end
end

app/helpers/exec_cn_machines_helper.rb
module ExecCnMachinesHelper
end

app/views/exec_cn_machines/_form.html.erb
<%= form_for(@exec_cn_machine) do |f| %>
  <% if @exec_cn_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exec_cn_machine.errors.count, "erreur") %> interdit la sauvegarde de l'application de la CN:</h2>

      <ul>
      <% @exec_cn_machine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <table border=0>
<tr><td>
<label for="type_exec_cn_machine_id_machine">Immatriculation :</label></td>
<td>
<%=  f.select  "id_machine", Machine.all.collect {|p| [ p.Immatriculation, p.id ] },{:include_blank=> 'Aucune'} %><br/>
</td></tr>
<tr><td>
<label for="exec_cn_machine_date_visite">date de visite:</label></td>
<td><%= f.date_select  "date_exec", :order => [:day,:month,:year],:start_year => 1980, :use_month_names=>@tableau_mois %>
<br/>
</td></tr>
<tr><td><%= label_tag(:non_applicable, "CN non applicable :") %></td>
<td><%= check_box "exec_cn_machine","non_applicable"%>
</td></tr>
<tr><td>
<label for="type_exec_cn_machine_id_cn_machine">Type de visite</label></td>
<td>
<%=  f.select( "idcn_machine", CnMachine.all.collect {|p| [ p.nom + " BS:" + p.service_bulletin, p.id ] },{:include_blank=> 'N.D'})%> 

</td></tr>
<tr><td>
<label for="exec_cn_machine_val_potentiel">faites &agrave; :</label><div id="unitee"> </div></td>
<td><%= f.text_field  "val_potentiel_exec", :size => 20 %>
</td></tr>
<tr><td>
<label for="exec_cn_machine_machine_commentaire">commentaires:</label></td>
<td><%= f.text_area "commentaire", :rows => 5, :cols => 20 %><br/>

</td></tr>
<tr><td>
  <p>
  <%= if !(params[:id_machine].nil?) then hidden_field_tag(:retour,params[:id_machine]) end %>
    <%= f.submit 'Sauvegarder' %>
  </p>

</td></tr>
</table>
<% end %>

app/views/exec_cn_machines/cn_typemachine.js.erb
(new_options = [
<%@cn_machines.each do |cn_machine| %>
["<%=cn_machine.nom + " BS:" + cn_machine.service_bulletin%>","<%=cn_machine.id%>"],
<%end%>
]);

/* Remove all options from the select list */
$('#exec_cn_machine_idcn_machine').empty();
$.each(new_options, function() {
                   $('#exec_cn_machine_idcn_machine').append(
                                        $("<option></option>").val(this[1]).html(this[0])
                                    )
                            });


app/views/exec_cn_machines/edit.html.erb
<h1>modification de l'application CN Machine</h1>

<%= render 'form' %>

<%= link_to 'Détails', @exec_cn_machine %> |
<%= link_to 'retour à la liste des exécutions CN machine', exec_cn_machines_path %>

app/views/exec_cn_machines/index.html.erb
<h1>Applications des CN </h1>
<% typ="" %>
<% mach=""%>
<br><%= link_to "saisie d'une application de CN", new_exec_cn_machine_path %></br>
<% @exec_cn_machines.each do |exec_cn_machine| %>
	<% if (typ!=exec_cn_machine.machine.Immatriculation+exec_cn_machine.cn_machine.nom) then %>
	<% if typ!="" then %> </table>  <%end %>
	<%typ=exec_cn_machine.machine.Immatriculation+exec_cn_machine.cn_machine.nom%>
	<% if (mach!= exec_cn_machine.machine.Immatriculation) then %>
		<% mach=exec_cn_machine.machine.Immatriculation %>
		<h3><%= exec_cn_machine.machine.type_machine.type_machine%> <%= exec_cn_machine.machine.Immatriculation%> </h3>
	<% end %>
	<h4><%= exec_cn_machine.cn_machine.nom %></h4>
	<table border=1 width= 60% >
	  <tr>
		<td width= 15%>Numéro BS</td>
		<td width= 10%>date execution</td>
		<td width= 10%>Potentiel à execution</td>
		<td width= 10%>CN applicable</td>
		<td width= 5%>&nbsp;</td>
		<td width= 5%>&nbsp;</td>
		<td width= 5%>&nbsp;</td>
	  </tr>
	<%end%>
  <tr>
    <td><%= exec_cn_machine.cn_machine.service_bulletin %></td>
    <td><%= exec_cn_machine.date_exec.strftime('%d/%m/%Y') %></td>
    <td>
    <% if ( exec_cn_machine.non_applicable or exec_cn_machine.cn_machine.type_potentiel.type_potentiel=="Une fois" or exec_cn_machine.cn_machine.type_potentiel.type_potentiel=="Calendaire") then " " else 
		exec_cn_machine.val_potentiel_exec.to_s + exec_cn_machine.cn_machine.type_potentiel.unitee 
		end%>
    </td>
    <td align="center"><%= if (!exec_cn_machine.non_applicable) then image_tag "case_a_cocher.gif" else image_tag "case_cocher_vide.jpg" end %></td>
    <td><%= link_to 'détails', exec_cn_machine %></td>
    <td><%= link_to 'modifier', edit_exec_cn_machine_path(exec_cn_machine) %></td>
    <td><%= link_to 'Suppr', exec_cn_machine, data: { confirm: 'êtes vous sur?'}, :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/exec_cn_machines/new.html.erb
<h1>Application CN Machine</h1>

<%= render 'form' %>
<%= link_to 'retour à la liste des execution CN machine', exec_cn_machines_path %>

app/views/exec_cn_machines/show.html.erb
<h1> détail de l'application de la CN </h1>
<table border=1>
  <tr>
	<td>Machine</td>
	<td>CN</td>
	<td>Numéro BS</td>
	<td>date execution</td>
	<td>Potentiel à execution</td>
	<td>CN applicable</td>
	<td>Commentaires</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
  </tr>


  <tr>
    <td><%= @exec_cn_machine.machine.Immatriculation %></td>
    <td><%= @exec_cn_machine.cn_machine.nom  %></td>
    <td><%= @exec_cn_machine.cn_machine.service_bulletin %></td>
    <td><%= @exec_cn_machine.date_exec.strftime('%d/%m/%Y') %></td>
    <td>
    <%= if ( @exec_cn_machine.non_applicable or @exec_cn_machine.cn_machine.type_potentiel.type_potentiel=="Une fois" or @exec_cn_machine.cn_machine.type_potentiel.type_potentiel=="Calendaire") then " " 
		else 
		@exec_cn_machine.val_potentiel_exec + @exec_cn_machine.cn_machine.type_potentiel.unitee 
	end%>
    </td>
    
        <td align="center"><%= if (!@exec_cn_machine.non_applicable) then image_tag "case_a_cocher.gif" else  image_tag "case_cocher_vide.jpg" end %></td>
	<td align="center"><%=@exec_cn_machine.commentaire %></td>
    
	
    <td><%= link_to 'modifier', edit_exec_cn_machine_path(@exec_cn_machine) %></td>
    <td><%= link_to 'Suppr', @exec_cn_machine, data:{ confirm: 'êtes vous sur?'}, :method => :delete %></td>
  </tr>

</table>
<%= link_to 'Modifier', edit_exec_cn_machine_path(@exec_cn_machine) %> |
<%= link_to 'Retour', exec_cn_machines_path %>