config/routes.rb
KardexIII::Application.routes.draw do
  resources :equipement_vaut_pours

  resources :vaut_pours

  resources :est_monte_surs do 
	  collection do
		  get 'val_pot'
	  end
  end
  

  resources :equipements

  resources :visite_equipements do 
	  collection do
		get  'get_visite_equ'
		get 'get_type_visite'
	end
end

  resources :exec_cn_equipements do 
	  collection do
		get  'cn_type_equipement'
	end
end
  
  

  resources :cn_equipements

  resources :potentiel_equipements

  resources :visite_protocolaire_equipements

  resources :type_equipements

  resources :modif_repars

  resources :visite_machines do
	  collection do
		  get 'get_type_visite'
		  get 'get_type_machine'
	  end
  end
  

  resources :exec_cn_machines do
	collection do
		get 'cn_typemachine'
	end
end

  resources :doc_divers do
	  collection do
		  get 'envoi_doc'
		  post 'save_doc'
		  post 'suppr_doc'
	  end
  end
  
  resources :potentiel_machines 
  
  resources :type_potentiels  do
	  collection do
		  get 'get_unitee'
	  end
  end

  resources :cn_machines

  resources :visite_protocolaires

  resources :type_machines

  resources :machines

  resources :carnets

  resources :page_acces

  resources :personnes

resources :personnes do
end

resources :appli do
  collection do
    get 'login'
    post 'login'
    post 'create_new'
    get 'logout'
    get 'welcome'
    get 'bandeau_gauche'
  end
end
resources :machines do
end

  root :to => 'appli#welcome'
end

app/models/cn_machine.rb
class CnMachine < ActiveRecord::Base
	belongs_to:type_potentiel, :foreign_key =>:idtype_potentiel
	belongs_to:type_machine, :foreign_key =>:idtype_machine
	has_many:exec_cn_machine,:foreign_key=>:id_cn_machine
	validates_presence_of :val_potentiel ,:message => "le potentiel doit etre défini"
	validates_presence_of :idtype_potentiel, :message => "le type de potentiel doit etre défini"
	validates_presence_of :idtype_machine, :message => "le type de machine  doit etre défini"
end

app/controllers/cn_machines_controller.rb
class CnMachinesController < ApplicationController
  before_action :set_cn_machine, only: [:show, :edit, :update, :destroy]

  # GET /cn_machines
  # GET /cn_machines.json
  def index
    @cn_machines = CnMachine.all.includes(:type_potentiel,:type_machine)
    @cn_machines=@cn_machines.sort_by {|cn_machine| [cn_machine.type_machine.Nom_constructeur, cn_machine.type_machine.type_machine,cn_machine.reference]}
  end

  # GET /cn_machines/1
  # GET /cn_machines/1.json
  def show
	@cn_machine = CnMachine.find(params[:id])
	@cn_docs=DocDiver.find(:all,:conditions=>["type_doc_id=1 and id_entite=?",params[:id]])
	@bs_docs=DocDiver.find(:all,:conditions=>["type_doc_id=3 and id_entite=?",params[:id]])
  end

  # GET /cn_machines/new
  def new
    @cn_machine = CnMachine.new
    if !(params[:idtype_machine].nil?) then 
		@cn_machine.idtype_machine=params[:idtype_machine]
	end
  end

  # GET /cn_machines/1/edit
  def edit
	@cn_docs=DocDiver.find(:all,:conditions=>["type_doc_id=1 and id_entite=?",params[:id]])
	@bs_docs=DocDiver.find(:all,:conditions=>["type_doc_id=3 and id_entite=?",params[:id]])
	@doc=DocDiver.new
	 #doc = cn machine par défaut
	@doc.type_doc_id=1
  end

  # POST /cn_machines
  # POST /cn_machines.json
  def create
   @cn_machine = CnMachine.new(params[:cn_machine].permit(:idtype_machine,:date_premiere_execution,:reference,:service_bulletin,:est_annule,:idtype_potentiel,:val_potentiel,:nom,:commentaire))

    respond_to do |format|
      if @cn_machine.save
        format.html {
		#a faire un test si param retour on redirige sur le type machine sinon on reboucle sur la liste des VP
		if (params[:retour].nil?) then 
			redirect_to(@cn_machine, :notice => 'la Cn a ete cree.') 
		else
			@type_machine = TypeMachine.find(params[:retour])
			@visite_protocolaires=VisiteProtocolaire.find_all_by_idtype_machine(params[:retour])
			@potentiel_machines=PotentielMachine.find_all_by_idtype_machine(params[:retour])
			@cn_machines=CnMachine.find_all_by_idtype_machine(params[:retour])
			render 'type_machines/show',:notice => 'la Cn a ete cree.'
		end	
		}
        format.xml  { render :xml => @cn_machine, :status => :created, :location => @cn_machine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cn_machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cn_machines/1
  # PATCH/PUT /cn_machines/1.json
  def update
    respond_to do |format|
      if @cn_machine.update(cn_machine_params.permit(:idtype_machine,:date_premiere_execution,:reference,:service_bulletin,:est_annule,:idtype_potentiel,:val_potentiel,:nom,:commentaire))
        format.html { redirect_to @cn_machine, notice: 'Cn machine correctement mis à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cn_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cn_machines/1
  # DELETE /cn_machines/1.json
  def destroy
    @cn_machine.destroy
    respond_to do |format|
      format.html { redirect_to cn_machines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cn_machine
      @cn_machine = CnMachine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cn_machine_params
      params[:cn_machine]
    end
end

app/helpers/cn_machines_helper.rb
module CnMachinesHelper
end

app/views/cn_machines/_form.html.erb
<%= form_for(@cn_machine) do |f| %>
  <% if @cn_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cn_machine.errors.count, "error") %> prohibited this cn_machine from being saved:</h2>

      <ul>
      <% @cn_machine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table border=1>
<tr><td>
<label for="cn_machine_Nom">Nom :</label></td>
<td><%= text_field "cn_machine", "nom", :size => 20 %><br/>
</td></tr>
<tr><td>
<label for="cn_machine_reference">Reference CN :</label></td>
<td><%= text_field "cn_machine", "reference", :size => 20 %><br/>
</td></tr>
<tr><td>
<label for="cn_machine_service_bulletin">BS :</label></td>
<td><%= text_field "cn_machine", "service_bulletin", :size => 20 %><br/>
</td></tr>
<tr><td>
<label for="type_cn_machine_idtype_machine">type de machine:</label></td>
<td>
<%=  select("cn_machine", "idtype_machine", TypeMachine.all.collect {|p| [ p.type_machine, p.id ] })%><br/>
<%= if !(params[:idtype_machine].nil?) then hidden_field_tag(:retour,params[:idtype_machine]) end %>
</td></tr>
<tr><td><%= label_tag(:est_annule, "CN annulée") %></td>
<td><%= check_box "cn_machine","est_annule"%>
</td></tr>
<tr><td>
<label for="type_cn_machine_idtype_potentiel">type de potentiel:</label></td>
<td>
<%=  select("cn_machine", "idtype_potentiel", TypePotentiel.all.collect {|p| [ p.type_potentiel, p.id ] })%><br/>
</td></tr>

<tr><td>
<label for="cn_machine_valeur_potentiel">valeur du potentiel:</label></td>
<td><%= text_field "cn_machine", "val_potentiel", :size => 20 %><br/>
</td></tr>
<tr><td>
<label for="cn_machine_commentaire">commentaires:</label></td>
<td><%= text_area"cn_machine", "commentaire", :rows => 5, :cols => 20 %><br/>
</td></tr>
<tr><td>
  <p>
    <%= f.submit 'Sauvegarder' %>
  </p>
</p>
  </td></tr>
  </table>
<% end %>

app/views/cn_machines/edit.html.erb
<h1>Edition d'une consigne machine</h1>

<%= render 'form' %>

<%= link_to 'détail', @cn_machine %> |
<%= link_to 'retour à la liste des CN machine', cn_machines_path %>
<div style="border-style: none;width:40%;">
<h2>documents</h2>
<h3>CN</h3>
<table border=0>
	<% @cn_docs.each do |cn_doc| %>
	<tr>
		<td><%= link_to(cn_doc.Nom,url_for(:controller=>'doc_divers', :action=>'envoi_doc',:fichier=>cn_doc.adresse,:id=>0))%></td>
		<td><%=   link_to('supprimer '+cn_doc.Nom,url_for(:controller=>'doc_divers', :action=>'suppr_doc',:id_fichier=>cn_doc.id,:id=>0),:confirm => 'êtes vous sur?')%></td>
	</tr>
	<% end %>
</table>
<h3>BS</h3>
<table border=0>
	<% @bs_docs.each do |bs_doc| %>
	<tr>
		<td><%= link_to(bs_doc.Nom,url_for(:controller=>'doc_divers', :action=>'envoi_doc',:fichier=>bs_doc.adresse,:id=>0))%></td>
		<td><%=   link_to('supprimer '+bs_doc.Nom,url_for(:controller=>'doc_divers', :action=>'suppr_doc',:id_fichier=>bs_doc.id,:id=>0),:confirm => 'êtes vous sur?')%></td>
	</tr>
	<% end %>
</table>
</div>
<p></p>
<div style="border-style: solid;width:40%;">
<h3>Ajouter un document</h3>
<%= form_for(@doc, :url => url_for(:action => 'save_doc', :controller => 'doc_divers'),:html => { :multipart => true }) do |f| %>
    <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_machine.errors.count, "error") %> prohibited this type_machine from being saved:</h2>

      <ul>
      <% @type_machine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <label for="doc_Nom">Nom du document:</label>
  <%= text_field "doc", "Nom", :size => 20 %></p>
  <p><label for="doc_type_doc_id">type de document:</label>
<td>
<%=  select("doc", "type_doc_id", TypeDoc.all.collect {|p| [ p.abbrev,p.id ] })%><br/>
  </p>
  <p>
  <%= hidden_field "doc","id_entite",:value=>@cn_machine.id %>
  <label for="doc_doc">document:</label><%= file_field 'upload', 'datafile' %></p>
  <%= f.submit 'Enregistrer' %>
  <% end %>
</div>

app/views/cn_machines/index.html.erb
<h1>liste des CN machines</h1>
<% type_machine="" %>
<p><%= link_to 'nouvelle CN machine', new_cn_machine_path %></p>
<% @cn_machines.each do |cn_machine| %>
	<% if cn_machine.type_machine.type_machine != type_machine then%>
		<%if (type_machine != "") then %></table> <% else %><% end %>
		<% type_machine = cn_machine.type_machine.type_machine%>
		<h3><%= cn_machine.type_machine.Nom_constructeur + ' '+cn_machine.type_machine.type_machine %></h3>
		<table border=1 width= 80%>
		  <tr>
			<td width=30%>Nom</td>
			<td width=20%>Reference</td>
			<td width=10%>BS</td>
			<td width=5%>Valide</td>
			<td width=14%>potentiel</td>
			<td width=7%>&nbsp</td>
			<td width=7%>&nbsp</td>
			<td width=7%>&nbsp</td>
		  </tr>
		  
	<% end%>
	<% type_machine = cn_machine.type_machine.type_machine%>
	<% if (cn_machine.est_annule) then @style='id="annule"' else @style='' end%>
	  <tr>
		<td <%=@style%>><%= cn_machine.nom %></td>
		<td <%=@style%>><%= cn_machine.reference %></td>
		<td><%= cn_machine.service_bulletin %></td>
		<td align="center"><%= if (!cn_machine.est_annule) then image_tag "case_a_cocher.gif" else image_tag "case_cocher_vide.jpg" end %></td>
		<td><%= if (cn_machine.type_potentiel.unitee_saisie!="sans") then cn_machine.val_potentiel end %> <%= if (cn_machine.type_potentiel.unitee_saisie!="sans") then cn_machine.type_potentiel.unitee_saisie end %></td>
	    <td><%= link_to 'détail', cn_machine %></td>
	    <td><%= link_to 'Modifier', edit_cn_machine_path(cn_machine) %></td>
	    <td><%= link_to 'Supp', cn_machine, data:{ confirm: 'êtes vous sur?'}, :method => :delete %></td>
	  </tr>
<% end %>
</table>
<%= link_to 'nouvelle CN machine', new_cn_machine_path %>

app/views/cn_machines/new.html.erb
<h1>Nouvelle CN Machine</h1>

<%= render 'form' %>

<%= link_to 'retour à la liste des CN machine', cn_machines_path %>

app/views/cn_machines/show.html.erb
<h1>Détail Cn Machine</h1>
<p><%= link_to 'nouvelle CN machine', new_cn_machine_path %></p>
<table border=1>
  <tr>
	<td>Type Machine</td>
	<td>Nom</td>
	<td>Réference</td>
	<td>BS</td>
	<td>Valide</td>
	<td>potentiel</td>
	<td>Commentaires</td>
	<td>&nbsp</td>
	<td>&nbsp</td>
  </tr>

  <tr>
	<td><%= @cn_machine.type_machine.Nom_constructeur + @cn_machine.type_machine.type_machine %></td>
	<td><%= @cn_machine.nom %></td>
	<td><%= @cn_machine.reference %></td>
	<td><%= @cn_machine.service_bulletin %></td>
	<td align="center"><%= if (!@cn_machine.est_annule) then image_tag "case_a_cocher.gif" else image_tag "case_cocher_vide.jpg" end %></td>
	<td><%= @cn_machine.val_potentiel  %> <%= @cn_machine.type_potentiel.unitee_saisie %></td>
	<td align="center"><%=@cn_machine.commentaire %></td>
    <td><%= link_to 'Modifier', edit_cn_machine_path(@cn_machine) %></td>
    <td><%= link_to 'Supp', @cn_machine,  data:{ confirm: 'êtes vous sur?'}, :method => :delete %></td>
  </tr>
</table>
<p></p>
<div style="border-style: none;width:40%;">
<h2>documents</h2>
<h3>CN</h3>
<table border=0>
	<% @cn_docs.each do |cn_doc| %>
	<tr>
		<td><%= link_to(cn_doc.Nom,url_for(:controller=>'doc_divers', :action=>'envoi_doc',:fichier=>cn_doc.adresse,:id=>0))%></td>
	</tr>
	<% end %>
</table>

<h3>BS</h3>
<table border=0>
	<% @bs_docs.each do |bs_doc| %>
	<tr>
		<td><%= link_to(bs_doc.Nom,url_for(:controller=>'doc_divers', :action=>'envoi_doc',:fichier=>bs_doc.adresse,:id=>0))%></td>
	</tr>
	<% end %>
</table>
</div>
<%= if !(params[:id_machine].nil?) then link_to 'retour detail machine',url_for(:controller => 'machines',:action=>"show", :id => params[:id_machine],:onglet =>2)  else  link_to 'retour à la liste', cn_machines_path end%>