config/routes.rb
KardexIII::Application.routes.draw do
  resources :equipement_vaut_pours

  resources :vaut_pours

  resources :est_monte_surs do 
	  collection do
		  get 'val_pot'
	  end
  end
  

  resources :equipements

  resources :visite_equipements do 
	  collection do
		get  'get_visite_equ'
		get 'get_type_visite'
	end
end

  resources :exec_cn_equipements do 
	  collection do
		get  'cn_type_equipement'
	end
end
  
  

  resources :cn_equipements

  resources :potentiel_equipements

  resources :visite_protocolaire_equipements

  resources :type_equipements

  resources :modif_repars

  resources :visite_machines do
	  collection do
		  get 'get_type_visite'
		  get 'get_type_machine'
	  end
  end
  

  resources :exec_cn_machines do
	collection do
		get 'cn_typemachine'
	end
end

  resources :doc_divers do
	  collection do
		  get 'envoi_doc'
		  post 'save_doc'
		  post 'suppr_doc'
	  end
  end
  
  resources :potentiel_machines 
  
  resources :type_potentiels  do
	  collection do
		  get 'get_unitee'
	  end
  end

  resources :cn_machines

  resources :visite_protocolaires

  resources :type_machines

  resources :machines

  resources :carnets

  resources :page_acces

  resources :personnes

resources :personnes do
end

resources :appli do
  collection do
    get 'login'
    post 'login'
    post 'create_new'
    get 'logout'
    get 'welcome'
    get 'bandeau_gauche'
  end
end
resources :machines do
end

  root :to => 'appli#welcome'
end

app/models/machine.rb
class Machine < ActiveRecord::Base
belongs_to:type_machine, :foreign_key =>:type_machine_idtype_machine
validates_presence_of :type_machine_idtype_machine ,:message => "le type de machine ne peut etre vide"
validates_presence_of :Immatriculation ,:message => "l'immatriculation ne peut etre vide"
validates_presence_of :num_serie, :message => "le numéro de série ne peut etre vide"
validates_presence_of :date_construct, :message => "la date de construction ne peut être vide"
has_many :modif_repar, :foreign_key =>:id_machine
has_many :montage_equipement, :foreign_key =>:idmachine


def self.couleur(id)
	# fait le tour de l'état d'une machine pour indiquer si probléme de maintien en navigabilité
	#couleur ( 0 = vert; 1 orange ; 2 rouge)
	# calcul des visites machines et equipement
	couleur=Machine.couleur_visite(id)
	#calcul des CN machine
	if (couleur<2) then
		cool=Machine.couleur_cn_machine(id)
		if (cool > couleur) then couleur=cool end
	end
	#calcul des CN équipement
	if (couleur<2) then
		cool=Machine.couleur_cn_equipement(id)
		if (cool > couleur) then couleur=cool end
	end
	if (couleur<2) then
		cool=Machine.couleur_potentiel_machine(id)
		if (cool > couleur) then couleur=cool end
	end
	
	return (couleur)
end
def self.tab_visite(id)
#récupère machine
	if !(id.nil?) then
		u=find(id)
		vis_pro=VisiteProtocolaire.find_all_by_idtype_machine(u.type_machine_idtype_machine)
		return nil if vis_pro.nil?
	else
		vis_pro=VisiteProtocolaire.all
	end
	j=0
	list=[]
	vis_pro.each do |vis_pro|
		list[j]=[vis_pro.Nom,vis_pro.id]
		j=j+1
	end
	return list
end
def self.couleur_visite(id)
	couleur=0
	# calcul des visites machines
	visites_machine=VisiteMachine.dernieres_visites(id)
	visites_machine.each do |visite|
		if (couleur<2) then
			#si le reste est négatif = rouge
			if (visite[1]["reste"]<0 )  then
				couleur =2 
			else
				reste=0.0
				#on traite en fonction du type de potentiel
				#on calcul le % restant 2 cas si calendaire ou si autre 
				if( visite[1]["visite_protocolaire"].type_potentiel.type_potentiel=="Calendaire") then 
					#potentiel calendaire différence en jours et potentiel en mois
					reste=visite[1]["reste"].to_f
					reste=reste/(visite[1]["visite_protocolaire"].valeur_potentiel.to_f*30.5)
				else
					#dans les autres cas de protentiel pas de soucis 
					reste = visite[1]["reste"].to_f/visite[1]["visite_protocolaire"].valeur_potentiel.to_f
				end
				if (reste<0.05) then couleur=1 end
			end
		end
	end
	#calcul des vistes équipement
	#calcul des visites équipement montée sur la machine 
	visites_equipement=VisiteEquipement.dernieres_visites(id)
	# visite par visite on regarde
	if (couleur<2) then
		visites_equipement.each do |visite|
			if (visite[1]["couleur"] > couleur) then couleur=visite[1]["couleur"] end
		end
	end
	return (couleur)
end

def self.couleur_cn_machine(id)
	couleur=0
	#calcul des application CN machine
	cn_machine=ExecCnMachine.etat_cn(id)
	cn_machine.each do |cn_ex|
		if (cn_ex[1]["couleur"] > couleur) then couleur=cn_ex[1]["couleur"] end
	end
	return (couleur)
end
def self.couleur_cn_equipement(id)
	cn_equipement_machine=ExecCnEquipement.etat_cn(id)
	couleur=0
	cn_equipement_machine.each do |cn_ex|
		if (cn_ex[1]["couleur"] > couleur) then couleur=cn_ex[1]["couleur"] end
	end
	return(couleur)
end
def self.couleur_potentiel_machine(id)
	couleur=0
	#calcul des potentiels machine
	pots_machs=PotentielMachine.potentiel_machine(id)
	pots_machs.each do |pot_mach|
		if (pot_mach["reste"] <0) then 
			couleur=2
		else
			if(pot_mach["type_potentiel"]=="Calendaire") then 
				#potentiel calendaire différence en jours et potentiel en mois
				reste=pot_mach["reste"].to_f 
				reste=reste/(pot_mach["val_potentiel"] .to_f)
				reste=reste/30.5
			else
				#dans les autres cas de protentiel pas de soucis 
				reste = pot_mach["reste"].to_f/pot_mach["val_potentiel"].to_f
			end
			if (reste<0.05) then couleur=1 end	
		end
	end
	#calcul des potentiels équipement
	if (couleur<2) then
		montages=Equipement.potentiel_restant_machine(id)
		#on prend équipement par équipement
		montages.each do |montage| 
			equipement=montage[1]["equipement"]
			#potentiel restant au montage de l'équipement 
			if (montage[1]["couleur"] > couleur) then couleur=montage[1]["couleur"] end
		end
	end
	return(couleur)
end


end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_cn_equipement.html.erb
<h2> Etat des CN Equipements</h2>
<% type_equip=0 %>
<% equip=""%>
<%lance_visite=EstAcce.page_acc("exec_cn_equipements","new",session[:personne].id_fonction)%>
<% @cn_equipement_machine.each do |cn_ex| %>
		<% if (equip!= cn_ex[1]["equipement_type"]) then %>
			<% if (equip!="") then %></table> <%end %>
			<%equip=cn_ex[1]["equipement_type"] %>
			<% if (type_equip!= cn_ex[1]["moteur_helice"]) then %>
				<% type_equip= cn_ex[1]["moteur_helice"]  %>
				<% if (type_equip==2) then%> <h3>Hélice</h3> <%end %>
				<% if (type_equip==1) then%> <h3>Moteur</h3> <%end %>
				<% if (type_equip==3) then%> <h3>Divers</h3> <%end %>
			<%end%>
			<h4><%=cn_ex[1]["equipement_type"]%></h4>
			<table border=1  width="100%" >
			 <tr>
			    <td>ref CN</td>
			    <td>Nom Cn</td>
			    <td>Num BS</p>
			    <td>valeur potentiel</p>
			    <td>date application</td>
			    <td>valeur potentiel</td>
			    <td>but&eacute;e</td>
			    <td>Derniere valeur connue </td>
			    <td>potentiel restant hors tol&eacute;rance</td>
			    <td> CN Applicable </td>
			    <% if (lance_visite) then %><td>&nbsp;</td><% end %>
			</tr>
		<% end %>
	<% cn_mach=cn_ex[1]["visite_protocolaire"] %>
	 <% @style=styling(cn_ex[1]["couleur"])%>
	 <% if (cn_ex[1]["visite_protocolaire"].est_annule) then @style='annule' end%>
	<tr>
		<td  id='<%= @style %>' ><%=  cn_mach.reference %></td>
		<td > <%=  link_to(cn_ex[1]["visite_protocolaire"].nom,url_for(:controller=>"cn_equipements", :action=>'show',:id=>cn_ex[1]["visite_protocolaire"].id,:id_machine=>@machine.id))  %> </td>
		<td><%=  cn_mach.service_bulletin %></td>
		<td><%=  cn_mach.val_potentiel.to_s%> <%= cn_mach.type_potentiel.unitee %></td>
		<% if cn_ex[1]["date_visite"]=="pas_applique" then @date_1=cn_ex[1]["date_visite"] else @date_1=cn_ex[1]["date_visite"].strftime('%d/%m/%Y') end %>
		<td><%=  @date_1 %></td>
		<td><%=  pres_val(cn_ex[1]["val_potentiel"], cn_mach.type_potentiel.type_potentiel) %></td>
		<td><%=  pres_val(cn_ex[1]["butee"], cn_mach.type_potentiel.type_potentiel) %></td>
		<td><%=  pres_val(cn_ex[1]["val_dernier_releve"],cn_mach.type_potentiel.type_potentiel) %></td>
		<td   id='<%= @style %>' ><%=  pres_pot(cn_ex[1]["reste"],cn_mach.type_potentiel.type_potentiel) %></td>
		<td align="center"><%= if (!cn_ex[1]["NA"]) then image_tag "case_a_cocher.gif" else " " end %></td>
		<% if (lance_visite) %><td><%= link_to 'nouvelle éxecution',new_exec_cn_equipement_path(:id_equipement=>cn_ex[1]["idequipement"],:idcn_equipement =>cn_mach.id,:id_machine=>@machine.id) %></td><%end%>
	</tr>
<% end %>
</table>

app/views/machines/edit.html.erb
<h1>Modifier une machine</h1>

<%= render 'form' %>

<%= link_to 'détail', @machine %> |
<%= link_to 'retour à la liste', machines_path %>

app/views/machines/index.html.erb
<h1>Liste des machines gérées</h1>
<%= link_to("imprimer l'état des CEN", "./machines.pdf") %>
<table border=1 >
  <tr>
    <td> type </td>
    <td> Nom Constructeur</td>
    <td>  Immatriculation </td>
    <td>  num série </td>
    <td>  date construction </td>
    <td>&nbsp</td>
    <% if (@modif)  %><td>&nbsp</td><%end%>
     <%if (@suppr)  %><td>&nbsp</td><%end%>
  </tr>

<% @machines.each do |mach| %>
	<% couleur= Machine.couleur(mach.id) %>
	<% if(couleur==2) then @style='KO' elsif (couleur==1) then @style='half_ko' else  @style='OK' end %>
  <tr>
	<td><%= mach.type_machine.type_machine%>
	<td><%= mach.type_machine.Nom_constructeur%>
	<td id='<%= @style %>' ><%=  mach.Immatriculation %></td>
	<td><%=  mach.num_serie %></td>
	<td><%=  mach.date_construct.strftime('%d/%m/%Y') %></td>
	<td><%= link_to 'détail', mach %></td>
	 <% if (@modif)  %><td><%= link_to 'modifier', edit_machine_path(mach) %></td><%end%>
	 <% if (@suppr)  %><td><%= link_to 'supprimer', mach, :confirm => 'êtes vous sur?', :method => :delete %></td><%end%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'créer une nouvelle machine', new_machine_path %>

app/views/machines/new.html.erb
<h1>Nouvelle machine</h1>

<%= render 'form' %>

<%= link_to 'retour à la liste', machines_path %>

app/views/machines/show.html.erb
<h1>Détail machine <%=@machine.Immatriculation%> </h1>
<%= link_to('imprimer la fiche', "./" + @machine.id.to_s + ".pdf") %>

	<div id="fx1"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:  50px; top:75px; z-index:5 ; border-bottom : <%=@onglet1[0]%> " onclick="active_onglet(1)"><b>donn&eacute;es g&eacute;n&eacute;rales </b></div>
	<div id="fx2"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:153px; top:75px; z-index:5; border-bottom : <%=@onglet1[1]%>" onclick="active_onglet(2)"> <b id='<%=styling(@couleur_visite)%>'>	Visites Entretien</b> </div>
	<div id="fx3"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:256px; top:75px; z-index:5; border-bottom : <%=@onglet1[2]%>" onclick="active_onglet(3)"><b id='<%=styling(@couleur_cn_machine)%>'>	CN machine </b> </div>
	<div id="fx4"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:359px; top:75px; z-index:5;border-bottom : <%=@onglet1[3]%>" onclick="active_onglet(4)"><b id='<%=styling(@couleur_cn_equipement)%>'>CN Equipement </b> </div>
	<div id="fx5"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:462px; top:75px; z-index:5;border-bottom : <%=@onglet1[4]%>" onclick="active_onglet(5)"><b id='<%=styling(@couleur_potentiel_machine)%>'>dur&eacute;e de vie</b></div>
	<div id="fx6"  style="position:absolute;background-color:#FFFFFF ; border: solid; width:100px; height:40px; left:565px; top:75px; z-index:5;border-bottom : <%=@onglet1[5]%>" onclick="active_onglet(6)"><b>Modification r&eacute;paration</b></div>

	
<div	id=f1 style="position:absolute; background-color:#FFFFFF ; border:solid; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900'); z-index:0";visibility:<%=@onglet[0]%>  >
<h2>Donn&eacute;es G&eacute;n&eacute;rales</h2>
<table border=0>
<tr>
<td>Constructeur:<td>
<%= @machine.type_machine.Nom_constructeur %>
</td>

<td>Type:<td>
<%= @machine.type_machine.type_machine %>
</td>
</tr><tr>
<td>Immatriculation:
<td>
<%= @machine.Immatriculation %>
</td><td>Num&eacute;ro de s&eacute;rie </td><td>
<%= @machine.num_serie %>
</td></tr>
<tr><td>Date de construction </td><td>
<%= @machine.date_construct.strftime('%d/%m/%Y') %>
</td>
<td>
 Age de la machine : </td><td><%= @age_annee  %> ann&eacute;es et <%= @age_mois  %> mois
</td></tr>
</table>
<% if (EstAcce.page_acc("machines","edit",session[:personne].id_fonction))  %><%= link_to 'modifier', edit_machine_path(@machine) %> |<%end%>
<%= link_to 'retour à la liste', machines_path %>
<h2> Dernier relev&eacute;</h2>
<p>date du relev&eacute :<%= @releve["date_releve"].strftime('%d/%m/%Y') %></p>
<table border=1>
<tr><td>&nbsp;</td><td>valeur relev&eacute; </td><td>utilisation annuelle</td></tr>
<tr><td>Heure de vol </td><td><%= @releve["heure_de_vol"] %></td><td><%= sprintf("%.0f",@util["heure_de_vol"]) %></td></tr>
<tr><td>Nombre de Cycle </td><td><%= @releve["nombre_cycle"]%></td><td><%=sprintf("%.0f",@util["nombre_cycle"]) %></tr>
<tr><td>Heure moteur</td><td><%= @releve["heure_moteur"]%></td><td><%=sprintf("%.0f",@util["heure_moteur"]) %></tr>
</table>
<h2>Equipements mont&eacute;s sur la machine</h2>
<table border=1>
<tr>
	<td>Constructeur</td>
	<td>Type </td>
	<td>Num s&eacute;rie</td>
	<td>date montage</td>
</tr>
<% @equipement.each do |equipement1| %>
<tr>
	<td><%= equipement1.equipement.type_equipement.nom_constructeur %></td>
	<td><%= equipement1.equipement.type_equipement.type_equipement %></td>
	<td><%= equipement1.equipement.num_serie %></td>
	<td><%= equipement1.date_montage.strftime('%d/%m/%Y')%></td>
</tr>
<% end %>
</table>
<div style="border-style: none;width:40%;">
<h2>documents</h2>
<h3>Manuels de maintenance Machine</h3>
<table border=0>
	<% @mm_docs.each do |mm_doc| %>
	<tr>
		<td><%= link_to(mm_doc.Nom,url_for(:controller=>'doc_divers', :action=>'envoi_doc',:fichier=>mm_doc.adresse,:id=>0))%></td>
	</tr>
	<% end %>
</table>
</div>
</div>

<div	id=f2 style="position:absolute; background-color:#ffffFF;border:solid; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900') ; z-index:0 ;visibility:<%=@onglet[1]%>">
<h2> Etat des visites entretien machine</h2>
<table border=1>
 <tr>
    <td>Visite</td>
    <td>P&eacute;riodicit&eacute;</p>
    <td>Tol&eacute;rance</p>
    <td>derni&egrave;re visite</td>
    <td>Date visite</td>
    <td>valeur potentiel</td>
    <td>but&eacute;e</td>
    <td>but&eacute;e avec tol</td>
    <td>Derniere valeur connue </td>
    <td>potentiel restant hors tol&eacute;rance</td>
    <td>potentiel restant avec tol&eacute;rance</td>
    <%lance_visite=EstAcce.page_acc("visite_machines","new",session[:personne].id_fonction)%>
    <% if (lance_visite) then %><td>cr&eacute;er une nouvelle visite</td><%end%>
    
</tr>
<% @visite_machines.each do |visite| %>
   <% vi_pro=visite[1]["visite_protocolaire"] %>
   <% if (visite[1]["couleur"]==2) then @style='id="KO"' elsif  (visite[1]["couleur"]==1) then @style='id="half_ko"'  else @style='id="OK"'  end %>
  <tr>
    <td  id='<%=styling(visite[1]["couleur"])%>' ><%=  visite[1]["visite_protocolaire"].Nom %></td>
    <td><%=  visite[1]["visite_protocolaire"].valeur_potentiel.to_s%> <%= visite[1]["visite_protocolaire"].type_potentiel.unitee %></td>
    <td><%=  visite[1]["visite_protocolaire"].tolerance.to_s %> <%= visite[1]["visite_protocolaire"].type_potentiel.unitee %></td>
    <td><%=  visite[1]["nom"] %></td>
    <td><%=  visite[1]["date_visite"].strftime('%d/%m/%Y') %></td>
    <td><%=  if( visite[1]["visite_protocolaire"].type_potentiel.type_potentiel=="Calendaire") then visite[1]["val_potentiel"].strftime('%d/%m/%Y') else number_with_precision(visite[1]["val_potentiel"],precision:2, locale: :fr) end%></td>
    <td><%=  if( visite[1]["visite_protocolaire"].type_potentiel.type_potentiel=="Calendaire") then visite[1]["butee"].strftime('%d/%m/%Y') else visite[1]["butee"] end%></td>
    <td><%=  if( visite[1]["visite_protocolaire"].type_potentiel.type_potentiel=="Calendaire") then visite[1]["butee_tol"].strftime('%d/%m/%Y') else visite[1]["butee_tol"] end%></td>
    <td><%=  if( visite[1]["visite_protocolaire"].type_potentiel.type_potentiel=="Calendaire") then visite[1]["val_dernier_releve"].strftime('%d/%m/%Y') else visite[1]["val_dernier_releve"] end%></td>
    <td  id='<%=styling(visite[1]["couleur"])%>' ><%= pres_pot(visite[1]["reste"], visite[1]["visite_protocolaire"].type_potentiel.type_potentiel)%></td>
    <td><%=pres_pot(visite[1]["reste_tol"], visite[1]["visite_protocolaire"].type_potentiel.type_potentiel)%></td>
    <% if (lance_visite)   %><td><%= link_to 'nouvelle visite',new_visite_machine_path(:id_machine=>@machine.id,:id_visite_pro =>vi_pro.id), :data => { :no_turbolink => true } %></td><%end%>
  </tr>
<% end %>
</table>
 <% if (lance_visite)   then %><%= link_to 'nouvelle visite',new_visite_machine_path(:id_machine=>@machine.id) %><%end%>

		<%= render "visite_equipement" %>
</div>
<div	id=f3 style=" position:absolute; background-color:#FFFFFF;  border:solid ; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900') ; z-index:0 ;visibility:<%=@onglet[2]%>">
<h2> Etat des CN Machines</h2>
<table border=1>
 <tr>
    <td>R&eacute;f&eacute;rence</td>
    <td>Nom Cn</td>
    <td>Num BS</p>
    <td>valeur potentiel</p>
    <td>date application</td>
    <td>CN Applicable </td>
    <td>valeur potentiel</td>
    <td>but&eacute;e</td>
    <td>Derniere valeur connue </td>
    <td>potentiel restant hors tol&eacute;rance</td>
    <%lance_visite=EstAcce.page_acc("exec_cn_machines","new",session[:personne].id_fonction)%>
    <% if (lance_visite) then %><td>&nbsp;</td><%end%>
    
</tr>
<% @cn_machine.each do |cn_ex| %>
   <% cn_mach=cn_ex[1]["visite_protocolaire"] %>
  <tr>
     <% @style=styling(cn_ex[1]["couleur"])%>
     <% if (cn_ex[1]["visite_protocolaire"].est_annule) then @style="annule" end%>
    <td id='<%= @style %>' ><%=cn_mach.reference  %></td>
    <td  ><%=  link_to(cn_ex[1]["visite_protocolaire"].nom,url_for(:controller=>"cn_machines", :action=>'show',:id=>cn_ex[1]["visite_protocolaire"].id,:id_machine=>@machine.id,:idcn_machine =>cn_mach.id))  %></td>
    <td><%=  cn_mach.service_bulletin %></td>
    <td><%=  cn_mach.val_potentiel.to_s%> <%= cn_mach.type_potentiel.unitee %></td>
    <td><%=  cn_ex[1]["date_visite"] %></td>
    <td align="center"><%= if (!cn_ex[1]["NA"]) then image_tag "case_a_cocher.gif" else " " end %></td>
    <td><%= pres_val( cn_ex[1]["val_potentiel"],cn_mach.type_potentiel.type_potentiel)%></td>
    <td><%= pres_val( cn_ex[1]["butee"],  cn_mach.type_potentiel.type_potentiel) %></td>
    <td><%=  pres_val(cn_ex[1]["val_dernier_releve"],cn_mach.type_potentiel.type_potentiel)%></td>
    <td id='<%= @style %>'><%=  pres_pot( cn_ex[1]["reste"], cn_mach.type_potentiel.type_potentiel)%></td>
    <% if (lance_visite) then %><td><%= link_to 'nouvelle execution',new_exec_cn_machine_path(:id_machine=>@machine.id,:idcn_machine =>cn_mach.id) %></td><%end%>
      </tr>
<% end %>
</table>
	</div>
	
	
	<div	id=f4 style="position:absolute; background-color:#FFFFFF ; border:solid; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900') ; z-index:0 ;visibility:<%=@onglet[3]%>" >

		<%= render "cn_equipement" %>
	</div>
	<div	id=f5 style="position:absolute; background-color:#FFFFFF ; border:solid; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900') ; z-index:0 ;visibility:<%=@onglet[4]%>" >
	<h2> Machine </h2>
	<table border=1 width=40%>
<tr>
	<td>nom</td>
	<td>type de dur&eacute;e de vie</td>
	<td>dur&eacute;e de vie</td>
	<td>dur&eacute;e de vie restante</td>
	<td>But&eacute;e</td>
</tr>
	<% @pots_machs.each do |pot_mach| %>
	<% @style=styling(pot_mach["couleur"])%>
<tr>	
	<td   id='<%= @style %>' ><%=pot_mach["nom"] %></td>
	<td><%= pot_mach["type_potentiel"]  %></td>
	<td><%= pot_mach["val_potentiel"]  %></td>
	<td   id='<%= @style %>' ><%=pot_mach["reste"] %> <%= pot_mach["unitee"] %></td>
	<td><%=pot_mach["butee"] %></td>

</tr>
<% end %>
</table>	
<%= render "pot_equi" %>
	</div>
	
	<div	id=f6 style="position:absolute; background-color:#FFFFFF ; border:solid; width:1100px; height:4000px; left:10px; top:115px; clip:rect('0', '0', '900', '900') ; z-index:0 ;visibility:<%=@onglet[5]%>" >
	<h2> Modification R&eacute;paration </h2>
	<table border=1>
  <tr>
     <td>Immatriculation</td>
     <td>Service Bull</td>
     <td>Objet</td>
     <td>r&eacute;f&eacute;rence</td>
     <td>date r&eacute;alisation</td>
     <td>Fait par</td>
       <%lance_visite=EstAcce.page_acc("modif_repars","new",session[:personne].id_fonction)%>
    <% if (lance_visite) then %> <td>&nbsp;</td>
      <td>&nbsp;</td>
     <td>&nbsp;</td><%end%>
  </tr>

<% @modif_repars.each do |modif_repar| %>
  <tr>
    <td><%= modif_repar.machine.Immatriculation%></td>
    <td><%= modif_repar.sb %></td>
    <td><%= modif_repar.Objet%></td>
    <td><%= modif_repar.ref %></td>
    <td><%= modif_repar.date_rel.strftime('%d/%m/%Y')%></td>
    <td><%= modif_repar.fait_par%></td>
    <% if (lance_visite) then %> 
    <td><%= link_to 'Détail', modif_repar %></td>
    <td><%= link_to 'Modifier', edit_modif_repar_path(modif_repar) %></td>
    <td><%= link_to 'suppr', modif_repar, :confirm => 'etes vous sur', :method => :delete %></td><% end %>
  </tr>
<% end %>
</table>
<% if (lance_visite) then %>  <%= link_to 'saisir nouvelle modif/réparation',new_modif_repar_path(:id_machine=>@machine.id) %><%end%>
	</div>